
export const indianStates: string[] = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const mockFuelPrices: { [key: string]: number } = {
  'Andhra Pradesh': 109.87,
  'Delhi': 94.72,
  'Maharashtra': 104.21,
  'Karnataka': 100.58,
  'Tamil Nadu': 101.40,
  'Telangana': 107.41,
  'Rajasthan': 104.88,
  'Madhya Pradesh': 106.47,
  'Kerala': 105.78,
  'Gujarat': 94.65,
  'Uttar Pradesh': 94.65,
  'West Bengal': 103.94,
  'Punjab': 96.56,
  'Haryana': 95.27,
  'Bihar': 105.18,
  'Odisha': 101.06,
  'Jharkhand': 97.81,
  'Chhattisgarh': 100.39,
  'default': 102.00,
};
